### ISSUE TITLE
Squish Squash...

### ISSUE THREAD

**Issue by TechDudie** [MihinMUD/Minetest-mud-mod#2]
Make mud a liquid that you can’t see through, so that you sink in mud

**Comment by MihinMUD** [comment]
ok i will work on it

**Comment by TechDudie** [comment]
Look at 
https://github.com/minetest/minetest_game/blob/master/mods/default/nodes.lua
Lines 2182-2224

**Comment by MihinMUD** [comment]
yes what is it?

**Comment by MihinMUD** [comment]
done :)

**Comment by MihinMUD** [comment]
but it is see through

**Comment by MihinMUD** [comment]
i think its done now
